ci: 修正

diff --git a/.github/workflows/pre-release.yml b/.github/workflows/pre-release.yml
--- a/.github/workflows/pre-release.yml
+++ b/.github/workflows/pre-release.yml
@@ -48,16 +48,6 @@ jobs:
     needs:
       - test
     steps:
-      - name: バージョン確認
-        run: |
-          REF_NAME="${{ github.ref_name }}"
-          PACKAGE_VERSION="v$(jq -r .version < package.json)"
-
-          if [[ "$REF_NAME" != "$PACKAGE_VERSION" ]]; then
-            echo "Error: GitHub ref_name ($REF_NAME) does not match package.json version ($PACKAGE_VERSION)"
-            exit 1
-          else
-
       - name: パラメーター
         run: |
           ref="${{ github.ref_name }}"
@@ -77,6 +67,16 @@ jobs:
         id: params
 
       - uses: actions/checkout@v4
+
+      - name: バージョン確認
+        run: |
+          RELEASE_VERSION="${{ steps.params.outputs.ver }}"
+          PACKAGE_VERSION="v$(jq -r .version < package.json)"
+
+          if [[ "$RELEASE_VERSION" != "$PACKAGE_VERSION" ]]; then
+            echo "Error: Release version ($RELEASE_VERSION) does not match package.json version ($PACKAGE_VERSION)"
+            exit 1
+          else
 
       - name: Node.js ${{ env.NODE_VERSION }}
         uses: actions/setup-node@v4
